#!/usr/bin/env node
// The Landmark Tracker records runtime (S-01T): capture a Destination Question
// Card (DQC) before any landmark, Spec or Wiki destination exists, evolve it
// without losing its origin, connect it to landmarks as they emerge, and
// rebuild the generated TRACKER.json projection from the records alone.
//
// Three rules shape it. Records are the only author: TRACKER.json is derived,
// never read back as source, and a rebuild from the same records is byte-for-
// byte identical. A write never destroys the previous valid file: every
// mutation is validated against the whole inventory, privacy-scanned and
// preflighted before the first byte is written, then published through the
// shared temp-then-rename path. And the renderer invents no progress: an
// unassessed card is shown as unassessed, a missing assessment makes an
// aggregate explicitly incomplete, and empty input has no distribution at all.
//
// Concurrency: `--expect-revision` refuses a write based on a stale read. It
// is a comparison, not a lock, and does not isolate two concurrent writers;
// see workbench/landmark-tracker/README.md.
import fs from 'node:fs';
import path from 'node:path';
import { assertSafeReadPath, assertSafeWritePath, declaredTracker, findRoot, isMainModule, writeSafeFile, TRACKER_COLLECTIONS } from './workbench-paths.mjs';
import { allocateVisibleId, compareVisibleIds, visibleIdKey, visibleIdParts } from './visible-ids.mjs';
import { scanPrivacy } from './privacy.mjs';

// The exact ordered documentation-progress vocabulary. These describe concept
// and documentation progress, never Task status or implementation effort.
export const STEPS = Object.freeze(['Idea', 'Aligning', 'Confirmed', 'Mapped', 'Planned', 'Journey', 'Review', 'Verified']);
export const DQC_PREFIX = 'DQC';
export const LANDMARK_PREFIX = 'LMK';
export const DQC_SCHEMA = 'landmark-tracker/destination-question@1';
export const LANDMARK_SCHEMA = 'landmark-tracker/landmark@1';
export const PROJECTION_SCHEMA = 'landmark-tracker/projection@1';
export const NO_LANDMARK = 'No landmark';
const QUESTIONS = 'destination-questions';
const LANDMARKS = 'landmarks';
const KINDS = Object.freeze({
  [QUESTIONS]: { prefix: DQC_PREFIX, schema: DQC_SCHEMA },
  [LANDMARKS]: { prefix: LANDMARK_PREFIX, schema: LANDMARK_SCHEMA }
});
const QUESTION_KEYS = ['answer', 'assessment', 'confirmation', 'expectedResult', 'history', 'id', 'landmarks', 'origin', 'question', 'result', 'revision', 'schema', 'sources', 'title', 'uncertainty'];
const LANDMARK_KEYS = ['history', 'id', 'importance', 'origin', 'revision', 'schema', 'summary', 'title'];
const NOTICE = 'Generated by workbench/tools/landmark-tracker.mjs rebuild from the destination-questions and landmarks records. Edit the records, never this file.';

export class TrackerRefusal extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.code = code;
    this.details = details;
  }
}

function refuse(code, message, details) {
  throw new TrackerRefusal(code, message, details);
}

function lstatOrNull(target) {
  try { return fs.lstatSync(target); } catch (error) {
    if (error.code === 'ENOENT') return null;
    throw error;
  }
}

function posixRelative(root, target) {
  return path.relative(root, target).split(path.sep).join('/');
}

// ---------------------------------------------------------------- discovery

function context(rootDir) {
  const root = path.resolve(rootDir);
  let declared;
  try { declared = declaredTracker(root); }
  catch (error) { refuse(error.code === 'invalid-tracker' ? 'invalid-manifest' : error.code ?? 'invalid-manifest', error.message); }
  if (!declared) refuse('tracker-undeclared', 'This room declares no Landmark Tracker root; add a landmarkTracker block to workbench/manifest.json (see workbench/landmark-tracker/README.md).');
  const trackerRoot = path.resolve(root, declared.root);
  const dirs = Object.fromEntries(TRACKER_COLLECTIONS.map(name => [name, path.resolve(root, declared.collections[name])]));
  for (const directory of [trackerRoot, ...Object.values(dirs)]) {
    try { assertSafeReadPath(root, directory); }
    catch (error) { refuse('unsafe-path', error.message); }
    const entry = lstatOrNull(directory);
    if (!entry) refuse('missing-collection', `${posixRelative(root, directory)} is declared but missing; create it as an ordinary directory.`);
    if (!entry.isDirectory()) refuse('unsafe-path', `${posixRelative(root, directory)} must be an ordinary directory.`);
  }
  return { root, declared, trackerRoot, dirs, projection: path.resolve(root, declared.projection) };
}

// --------------------------------------------------------------- validation

function isText(value) {
  return typeof value === 'string' && value.trim().length > 0 && value === value.trim();
}

function isToken(value) {
  return typeof value === 'string' && /^[^\s]+$/.test(value) && value.length <= 200;
}

function isStamp(value) {
  return typeof value === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/.test(value);
}

function isRevision(value) {
  return Number.isSafeInteger(value) && value >= 1;
}

function isPlainObject(value) {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function exactKeys(value, keys) {
  return isPlainObject(value) && JSON.stringify(Object.keys(value).sort()) === JSON.stringify([...keys].sort());
}

// A meaningful title names a concept: not blank, not padded, and not merely an
// identifier standing in for one.
function titleProblems(title, label) {
  if (!isText(title)) return [`${label} must be non-empty text without surrounding whitespace`];
  if (title.length > 200) return [`${label} must be at most 200 characters`];
  if (visibleIdParts(title)) return [`${label} must name the concept, not an identifier (${title})`];
  return [];
}

function sourceProblems(sources, label) {
  if (!Array.isArray(sources)) return [`${label} must be an array`];
  const problems = [];
  const seen = new Set();
  for (const source of sources) {
    if (!exactKeys(source, ['id', 'revision']) || !isToken(source.id) || !(source.revision === null || isToken(source.revision))) {
      problems.push(`${label} entries are {id, revision} with an identifier and a revision or null`);
      continue;
    }
    if (seen.has(source.id)) problems.push(`${label} repeats ${source.id}`);
    seen.add(source.id);
  }
  return problems;
}

function historyProblems(record) {
  const problems = [];
  if (!Array.isArray(record.history) || record.history.length === 0) return ['history must record at least the capture'];
  record.history.forEach((entry, index) => {
    if (!exactKeys(entry, ['at', 'changes', 'reason', 'revision'])) { problems.push(`history entry ${index + 1} must be {revision, at, reason, changes}`); return; }
    if (entry.revision !== index + 1) problems.push(`history entry ${index + 1} must carry revision ${index + 1}`);
    if (!isStamp(entry.at)) problems.push(`history entry ${index + 1} needs an ISO timestamp`);
    if (!isText(entry.reason)) problems.push(`history entry ${index + 1} needs a reason (why this changed)`);
    if (!Array.isArray(entry.changes) || entry.changes.length === 0 || entry.changes.some(change => !isPlainObject(change) || !isText(change.field))) problems.push(`history entry ${index + 1} must list its changes`);
  });
  if (record.history.at(-1)?.revision !== record.revision) problems.push('the last history entry must match the record revision');
  return problems;
}

function assessmentProblems(assessment, revision) {
  if (assessment === null) return [];
  if (!exactKeys(assessment, ['basis', 'contributions', 'evidence', 'revision'])) return ['assessment must be {contributions, basis, evidence, revision}'];
  const problems = [];
  const entries = isPlainObject(assessment.contributions) ? Object.entries(assessment.contributions) : null;
  if (!entries || entries.length === 0) problems.push('assessment contributions must name at least one step');
  else {
    for (const [step, fraction] of entries) {
      if (!STEPS.includes(step)) problems.push(`assessment step ${step} is not in the vocabulary ${STEPS.join(', ')}`);
      if (typeof fraction !== 'number' || !Number.isFinite(fraction) || fraction <= 0 || fraction > 1) problems.push(`assessment fraction for ${step} must be greater than 0 and at most 1`);
    }
    const total = entries.reduce((sum, [, fraction]) => sum + (typeof fraction === 'number' ? fraction : 0), 0);
    if (Math.abs(total - 1) > 1e-9) problems.push(`assessment fractions must sum to 1; they sum to ${total}`);
  }
  if (!isText(assessment.basis)) problems.push('assessment needs a basis stating how its fractions were judged');
  if (!Array.isArray(assessment.evidence) || assessment.evidence.length === 0 || assessment.evidence.some(item => !isText(item))) problems.push('assessment must name at least one piece of supporting evidence');
  if (!isRevision(assessment.revision) || assessment.revision > revision) problems.push('assessment revision must be a record revision');
  return problems;
}

export function validateQuestion(record) {
  if (!exactKeys(record, QUESTION_KEYS)) return [`a DQC record has exactly the fields ${QUESTION_KEYS.join(', ')}`];
  const problems = [];
  if (record.schema !== DQC_SCHEMA) problems.push(`schema must be ${DQC_SCHEMA}`);
  if (visibleIdParts(record.id)?.prefix !== DQC_PREFIX) problems.push(`id must be a ${DQC_PREFIX}- identity`);
  if (!isRevision(record.revision)) problems.push('revision must be a positive integer');
  problems.push(...titleProblems(record.title, 'title'));
  if (!isText(record.question)) problems.push('question must be non-empty text');
  if (!(record.answer === null || isText(record.answer))) problems.push('answer must be null (unanswered) or text');
  if (!(record.confirmation === null || (exactKeys(record.confirmation, ['basis', 'revision']) && isText(record.confirmation.basis) && isRevision(record.confirmation.revision)))) problems.push('confirmation must be null or {basis, revision}');
  if (!(record.expectedResult === null || (exactKeys(record.expectedResult, ['change', 'home', 'revision']) && isText(record.expectedResult.change) && (record.expectedResult.home === null || isText(record.expectedResult.home)) && isRevision(record.expectedResult.revision)))) problems.push('expectedResult must be null or {change, home, revision}; a home without an intended change is not an Expected result');
  if (!(record.result === null || (exactKeys(record.result, ['revision', 'summary']) && isText(record.result.summary) && isRevision(record.result.revision)))) problems.push('result must be null or {summary, revision}');
  if (!Array.isArray(record.uncertainty) || record.uncertainty.some(item => !isText(item)) || new Set(record.uncertainty).size !== record.uncertainty.length) problems.push('uncertainty must be a list of distinct texts');
  problems.push(...sourceProblems(record.sources, 'sources'));
  if (!Array.isArray(record.landmarks) || record.landmarks.some(id => visibleIdParts(id)?.prefix !== LANDMARK_PREFIX) || new Set(record.landmarks).size !== record.landmarks.length) problems.push(`landmarks must be a list of distinct ${LANDMARK_PREFIX}- identities`);
  problems.push(...assessmentProblems(record.assessment, record.revision));
  const origin = record.origin;
  if (!exactKeys(origin, ['at', 'question', 'revision', 'sources', 'title']) || origin.revision !== 1 || !isStamp(origin.at) || !isText(origin.question) || titleProblems(origin.title, 'origin title').length || sourceProblems(origin.sources, 'origin sources').length) problems.push('origin must preserve the captured {title, question, sources, revision: 1, at}');
  problems.push(...historyProblems(record));
  return problems;
}

export function validateLandmark(record) {
  if (!exactKeys(record, LANDMARK_KEYS)) return [`a landmark record has exactly the fields ${LANDMARK_KEYS.join(', ')}`];
  const problems = [];
  if (record.schema !== LANDMARK_SCHEMA) problems.push(`schema must be ${LANDMARK_SCHEMA}`);
  if (visibleIdParts(record.id)?.prefix !== LANDMARK_PREFIX) problems.push(`id must be a ${LANDMARK_PREFIX}- identity`);
  if (!isRevision(record.revision)) problems.push('revision must be a positive integer');
  problems.push(...titleProblems(record.title, 'title'));
  if (!isText(record.summary)) problems.push('summary must be non-empty text');
  if (!(record.importance === null || isText(record.importance))) problems.push('importance must be null or text');
  const origin = record.origin;
  if (!exactKeys(origin, ['at', 'revision', 'summary', 'title']) || origin.revision !== 1 || !isStamp(origin.at) || !isText(origin.summary) || titleProblems(origin.title, 'origin title').length) problems.push('origin must preserve the captured {title, summary, revision: 1, at}');
  problems.push(...historyProblems(record));
  return problems;
}

function validateKind(kind, record) {
  return kind === QUESTIONS ? validateQuestion(record) : validateLandmark(record);
}

// ---------------------------------------------------------------- inventory

function loadInventory(ctx) {
  const inventory = { [QUESTIONS]: new Map(), [LANDMARKS]: new Map(), keys: new Map() };
  for (const kind of TRACKER_COLLECTIONS) {
    const directory = ctx.dirs[kind];
    const entries = fs.readdirSync(directory, { withFileTypes: true }).sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
    for (const entry of entries) {
      // .gitkeep and interrupted `.write-*` temporaries are not records.
      if (entry.name.startsWith('.')) continue;
      const full = path.join(directory, entry.name);
      const relative = posixRelative(ctx.root, full);
      if (entry.isSymbolicLink()) refuse('unsafe-path', `${relative} is a symbolic link; records are ordinary files inside the room.`);
      if (!entry.isFile() || !entry.name.endsWith('.json')) refuse('invalid-record', `${relative} is not a flat JSON record; collections hold only <ID>.json files.`);
      if (fs.lstatSync(full).nlink > 1) refuse('unsafe-path', `${relative} is hard-linked; records are ordinary files.`);
      let record;
      try { record = JSON.parse(fs.readFileSync(full, 'utf8')); }
      catch (error) { refuse('invalid-record', `${relative} is not valid JSON: ${error.message}`); }
      const problems = validateKind(kind, record);
      if (problems.length) refuse('invalid-record', `${relative} is not a valid ${kind} record: ${problems.join('; ')}`, { record: relative, problems });
      if (path.basename(entry.name, '.json') !== record.id) refuse('invalid-record', `${relative} holds ${record.id}; a record file is named by its identity.`, { record: relative });
      const key = visibleIdKey(record.id);
      if (inventory.keys.has(key)) refuse('identity-collision', `${record.id} in ${relative} collides with ${inventory.keys.get(key)}; one identity names one record.`, { record: relative, other: inventory.keys.get(key) });
      inventory.keys.set(key, relative);
      inventory[kind].set(record.id, { record, relative, full });
    }
  }
  checkRelations(inventory);
  return inventory;
}

function checkRelations(inventory) {
  for (const { record, relative } of inventory[QUESTIONS].values()) {
    for (const landmark of record.landmarks) {
      if (!inventory[LANDMARKS].has(landmark)) refuse('unknown-identity', `${record.id} (${relative}) links unknown landmark ${landmark}.`, { record: relative, landmark });
    }
  }
}

function findRecord(inventory, id) {
  const key = visibleIdKey(id);
  for (const kind of TRACKER_COLLECTIONS) {
    for (const [recordId, entry] of inventory[kind]) if (visibleIdKey(recordId) === key) return { kind, ...entry };
  }
  return null;
}

// --------------------------------------------------------------- projection

function round(value) {
  const rounded = Math.round(value * 1e6) / 1e6;
  return Object.is(rounded, -0) ? 0 : rounded;
}

// percentage = sum(contributions to step) / distinct item count * 100. Each
// distinct item is one unit; a mixed item contributes fractions summing to
// one. An unassessed item stays in the denominator and is named, so the
// aggregate is explicitly incomplete rather than silently filtered.
export function distribution(items) {
  const unique = [...new Map(items.map(item => [item.id, item])).values()].sort((a, b) => compareVisibleIds(a.id, b.id));
  if (unique.length === 0) return { items: 0, status: 'empty', counted: [], unassessed: [], distribution: null };
  const sums = Object.fromEntries(STEPS.map(step => [step, 0]));
  const unassessed = [];
  for (const item of unique) {
    if (!item.assessment) { unassessed.push(item.id); continue; }
    for (const [step, fraction] of Object.entries(item.assessment.contributions)) sums[step] += fraction;
  }
  const count = unique.length;
  return {
    items: count,
    status: unassessed.length ? 'incomplete' : 'complete',
    counted: unique.map(item => item.id),
    unassessed,
    distribution: Object.fromEntries(STEPS.map(step => [step, round((sums[step] * 100) / count)])),
    ...(unassessed.length ? { unassessedPercent: round((unassessed.length * 100) / count) } : {})
  };
}

function corrections(record) {
  return record.history.flatMap(entry => entry.changes
    .filter(change => change.field === 'correction')
    .map(change => ({ revision: entry.revision, text: change.to, reason: entry.reason })));
}

function questionCard(record, landmarks) {
  const titles = record.landmarks.map(id => landmarks.get(id).record.title);
  return {
    id: record.id,
    title: record.title,
    question: record.question,
    answer: record.answer,
    answered: record.answer !== null,
    confirmation: record.confirmation,
    expectedResult: record.expectedResult,
    result: record.result,
    uncertainty: record.uncertainty,
    landmarks: record.landmarks,
    landmarkDisplay: titles.length ? titles.join('; ') : NO_LANDMARK,
    assessment: record.assessment ? { state: 'assessed', ...record.assessment } : { state: 'unassessed' },
    distribution: distribution([{ id: record.id, assessment: record.assessment }]),
    sources: record.sources,
    origin: record.origin,
    corrections: corrections(record),
    revision: record.revision,
    history: record.history
  };
}

export function buildProjection(inventory) {
  const questions = [...inventory[QUESTIONS].values()].map(entry => entry.record).sort((a, b) => compareVisibleIds(a.id, b.id));
  const landmarks = [...inventory[LANDMARKS].values()].map(entry => entry.record).sort((a, b) => compareVisibleIds(a.id, b.id));
  const items = questions.map(record => ({ id: record.id, assessment: record.assessment }));
  return {
    schema: PROJECTION_SCHEMA,
    notice: NOTICE,
    steps: [...STEPS],
    workbench: distribution(items),
    landmarks: landmarks.map(record => {
      const members = questions.filter(question => question.landmarks.includes(record.id));
      return {
        id: record.id,
        title: record.title,
        summary: record.summary,
        importance: record.importance,
        questions: members.map(question => question.id),
        aggregate: distribution(members.map(question => ({ id: question.id, assessment: question.assessment }))),
        origin: record.origin,
        revision: record.revision,
        history: record.history
      };
    }),
    noLandmark: { display: NO_LANDMARK, questions: questions.filter(question => question.landmarks.length === 0).map(question => question.id) },
    questions: questions.map(record => questionCard(record, inventory[LANDMARKS]))
  };
}

function serialize(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

// ------------------------------------------------------------------- writes

function safeWrite(ctx, destination, content, options) {
  try { writeSafeFile(ctx.root, destination, content, options); }
  catch (error) {
    if (error.code === 'EEXIST') refuse('identity-collision', `${posixRelative(ctx.root, destination)} already exists; another writer published this identity first.`);
    throw error;
  }
}

function preflight(ctx, destination) {
  try { assertSafeWritePath(ctx.root, destination); }
  catch (error) { refuse('unsafe-path', error.message); }
}

// Validate everything, then write the changed records, then the projection.
// Nothing is written until every record, the whole resulting inventory, the
// privacy scan and every destination have passed.
function commit(ctx, inventory, changes) {
  const next = { [QUESTIONS]: new Map(inventory[QUESTIONS]), [LANDMARKS]: new Map(inventory[LANDMARKS]), keys: inventory.keys };
  const writes = [];
  for (const { kind, record, exclusive } of changes) {
    const problems = validateKind(kind, record);
    if (problems.length) refuse('invalid-record', `${record.id ?? 'the record'} would be invalid: ${problems.join('; ')}`, { problems });
    const content = serialize(record);
    const hits = scanPrivacy(content);
    if (hits.length) refuse('private-content', `${record.id} would carry private material (${[...new Set(hits.map(hit => hit.label))].join(', ')}); records are tracked in Git. Keep a safe reference instead.`, { labels: [...new Set(hits.map(hit => hit.label))] });
    const destination = path.join(ctx.dirs[kind], `${record.id}.json`);
    next[kind].set(record.id, { record, relative: posixRelative(ctx.root, destination), full: destination });
    writes.push({ destination, content, exclusive });
  }
  checkRelations(next);
  const projection = serialize(buildProjection(next));
  for (const write of writes) preflight(ctx, write.destination);
  preflight(ctx, ctx.projection);
  for (const write of writes) safeWrite(ctx, write.destination, write.content, { exclusive: write.exclusive });
  safeWrite(ctx, ctx.projection, projection);
  return writes.map(write => posixRelative(ctx.root, write.destination));
}

function nowStamp() {
  return new Date().toISOString();
}

function asList(value) {
  if (value === undefined) return [];
  return Array.isArray(value) ? value : [value];
}

function parseSources(values) {
  return asList(values).map((raw) => {
    const at = raw.lastIndexOf('@');
    return at > 0 ? { id: raw.slice(0, at), revision: raw.slice(at + 1) || null } : { id: raw, revision: null };
  });
}

function allocate(inventory, prefix, requested) {
  if (requested !== undefined) {
    if (visibleIdParts(requested)?.prefix !== prefix) refuse('invalid-record', `--id ${requested} must be a ${prefix}- identity.`);
    const other = inventory.keys.get(visibleIdKey(requested));
    if (other) refuse('identity-collision', `${requested} is already held by ${other}; retitle or revise that record instead of recapturing it.`, { other });
    return requested;
  }
  return allocateVisibleId(prefix, [...inventory.keys.values()].map(relative => path.basename(relative, '.json')));
}

function requireRevision(options, record) {
  const expected = Number(options['expect-revision']);
  if (record.revision !== expected) refuse('stale-revision', `${record.id} is at revision ${record.revision}, not ${options['expect-revision']}; reread it before writing.`, { current: record.revision });
}

// ----------------------------------------------------------------- commands

export function captureQuestion(rootDir, options = {}) {
  const ctx = context(rootDir);
  const inventory = loadInventory(ctx);
  const id = allocate(inventory, DQC_PREFIX, options.id);
  const at = nowStamp();
  const sources = parseSources(options.source);
  const record = {
    schema: DQC_SCHEMA,
    id,
    revision: 1,
    title: options.title,
    question: options.question,
    answer: options.answer ?? null,
    confirmation: null,
    expectedResult: null,
    result: null,
    uncertainty: asList(options.uncertainty),
    sources,
    landmarks: [],
    assessment: null,
    origin: { title: options.title, question: options.question, sources, revision: 1, at },
    history: [{ revision: 1, at, reason: options.reason, changes: [{ field: 'captured' }] }]
  };
  const [written] = commit(ctx, inventory, [{ kind: QUESTIONS, record, exclusive: true }]);
  return { status: 'captured', id, revision: 1, record: written, projection: ctx.declared.projection };
}

export function addLandmark(rootDir, options = {}) {
  const ctx = context(rootDir);
  const inventory = loadInventory(ctx);
  const id = allocate(inventory, LANDMARK_PREFIX, options.id);
  const at = nowStamp();
  const record = {
    schema: LANDMARK_SCHEMA,
    id,
    revision: 1,
    title: options.title,
    summary: options.summary,
    importance: options.importance ?? null,
    origin: { title: options.title, summary: options.summary, revision: 1, at },
    history: [{ revision: 1, at, reason: options.reason, changes: [{ field: 'captured' }] }]
  };
  const [written] = commit(ctx, inventory, [{ kind: LANDMARKS, record, exclusive: true }]);
  return { status: 'captured', id, revision: 1, record: written, projection: ctx.declared.projection };
}

function parseAssessment(raw) {
  const contributions = {};
  for (const part of String(raw).split(',')) {
    const split = part.indexOf('=');
    const step = part.slice(0, split).trim();
    const value = split > 0 ? Number(part.slice(split + 1)) : NaN;
    if (split < 1 || !STEPS.includes(step)) refuse('invalid-record', `--assess step ${JSON.stringify(step || part)} is not in the vocabulary ${STEPS.join(', ')}; done and similar statuses never stand in for a step.`);
    if (Object.hasOwn(contributions, step)) refuse('invalid-record', `--assess names ${step} twice.`);
    contributions[step] = value;
  }
  // Store in vocabulary order so identical assessments serialize identically.
  return Object.fromEntries(STEPS.filter(step => Object.hasOwn(contributions, step)).map(step => [step, contributions[step]]));
}

const QUESTION_REVISIONS = ['title', 'question', 'answer', 'confirm', 'expected-change', 'expected-home', 'source', 'uncertainty', 'resolve-uncertainty', 'correction', 'assess', 'basis', 'evidence'];
const LANDMARK_REVISIONS = ['title', 'summary', 'importance'];

function reviseQuestion(record, options, revision) {
  const next = structuredClone(record);
  const changes = [];
  for (const field of ['title', 'question', 'answer']) {
    if (options[field] !== undefined && options[field] !== record[field]) {
      changes.push({ field, from: record[field], to: options[field] });
      next[field] = options[field];
    }
  }
  if (options.confirm !== undefined) {
    next.confirmation = { basis: options.confirm, revision };
    changes.push({ field: 'confirmation', from: record.confirmation?.basis ?? null, to: options.confirm });
  }
  if (options['expected-change'] !== undefined || options['expected-home'] !== undefined) {
    next.expectedResult = {
      change: options['expected-change'] ?? record.expectedResult?.change,
      home: options['expected-home'] ?? record.expectedResult?.home ?? null,
      revision
    };
    changes.push({ field: 'expectedResult', from: record.expectedResult, to: next.expectedResult });
  }
  for (const source of parseSources(options.source)) {
    const existing = next.sources.find(item => item.id === source.id);
    if (!existing) {
      next.sources.push(source);
      changes.push({ field: 'source', from: null, to: source });
    } else if (existing.revision !== source.revision) {
      changes.push({ field: 'source', from: { ...existing }, to: source });
      existing.revision = source.revision;
    }
  }
  for (const text of asList(options.uncertainty)) {
    if (!next.uncertainty.includes(text)) { next.uncertainty.push(text); changes.push({ field: 'uncertainty', from: null, to: text }); }
  }
  for (const text of asList(options['resolve-uncertainty'])) {
    if (!next.uncertainty.includes(text)) refuse('invalid-record', `${record.id} records no uncertainty ${JSON.stringify(text)} to resolve.`);
    next.uncertainty = next.uncertainty.filter(item => item !== text);
    changes.push({ field: 'uncertainty', from: text, to: null });
  }
  for (const text of asList(options.correction)) changes.push({ field: 'correction', to: text });
  if (options.assess !== undefined) {
    next.assessment = { contributions: parseAssessment(options.assess), basis: options.basis, evidence: asList(options.evidence), revision };
    changes.push({ field: 'assessment', from: record.assessment?.contributions ?? null, to: next.assessment.contributions });
  } else if (options.basis !== undefined || options.evidence !== undefined) {
    refuse('invalid-record', '--basis and --evidence describe an assessment; supply them with --assess.');
  }
  return { next, changes };
}

function reviseLandmark(record, options) {
  const next = structuredClone(record);
  const changes = [];
  for (const field of LANDMARK_REVISIONS) {
    if (options[field] !== undefined && options[field] !== record[field]) {
      changes.push({ field, from: record[field], to: options[field] });
      next[field] = options[field];
    }
  }
  return { next, changes };
}

export function reviseRecord(rootDir, id, options = {}) {
  const ctx = context(rootDir);
  const inventory = loadInventory(ctx);
  const found = findRecord(inventory, id);
  if (!found) refuse('unknown-identity', `No Tracker record is named ${id}.`);
  const allowed = found.kind === QUESTIONS ? QUESTION_REVISIONS : LANDMARK_REVISIONS;
  const foreign = Object.keys(options).filter(key => [...QUESTION_REVISIONS, ...LANDMARK_REVISIONS].includes(key) && !allowed.includes(key));
  if (foreign.length) refuse('invalid-invocation', `${found.record.id} is a ${found.kind === QUESTIONS ? 'DQC' : 'landmark'}; it does not accept ${foreign.map(key => `--${key}`).join(', ')}.`);
  requireRevision(options, found.record);
  const revision = found.record.revision + 1;
  const { next, changes } = found.kind === QUESTIONS ? reviseQuestion(found.record, options, revision) : reviseLandmark(found.record, options);
  if (changes.length === 0) refuse('invalid-record', `This revision changes nothing in ${found.record.id}.`);
  next.revision = revision;
  next.history.push({ revision, at: nowStamp(), reason: options.reason, changes });
  commit(ctx, inventory, [{ kind: found.kind, record: next }]);
  return { status: 'revised', id: found.record.id, revision, record: found.relative, projection: ctx.declared.projection };
}

export function linkLandmark(rootDir, id, options = {}) {
  const ctx = context(rootDir);
  const inventory = loadInventory(ctx);
  const found = findRecord(inventory, id);
  if (!found || found.kind !== QUESTIONS) refuse('unknown-identity', `No DQC is named ${id}.`);
  requireRevision(options, found.record);
  const landmark = findRecord(inventory, options.landmark);
  if (!landmark || landmark.kind !== LANDMARKS) refuse('unknown-identity', `No landmark is named ${options.landmark}; capture it with add-landmark first.`);
  if (found.record.landmarks.includes(landmark.record.id)) refuse('invalid-record', `${found.record.id} is already linked to ${landmark.record.id}.`);
  const revision = found.record.revision + 1;
  const next = structuredClone(found.record);
  next.landmarks = [...next.landmarks, landmark.record.id].sort(compareVisibleIds);
  next.revision = revision;
  next.history.push({ revision, at: nowStamp(), reason: options.reason, changes: [{ field: 'landmarks', from: found.record.landmarks, to: next.landmarks }] });
  commit(ctx, inventory, [{ kind: QUESTIONS, record: next }]);
  return { status: 'linked', id: found.record.id, landmark: landmark.record.id, revision, record: found.relative, projection: ctx.declared.projection };
}

export function rebuildTracker(rootDir, options = {}) {
  const ctx = context(rootDir);
  const inventory = loadInventory(ctx);
  const content = serialize(buildProjection(inventory));
  const relative = ctx.declared.projection;
  if (options.check) {
    const entry = lstatOrNull(ctx.projection);
    const current = entry?.isFile() && !entry.isSymbolicLink() ? fs.readFileSync(ctx.projection, 'utf8') : null;
    if (current !== content) refuse('projection-drift', `${relative} does not match a rebuild from the records; run rebuild (never hand-edit the projection).`, { projection: relative });
    return { status: 'current', projection: relative };
  }
  preflight(ctx, ctx.projection);
  safeWrite(ctx, ctx.projection, content);
  return { status: 'rebuilt', projection: relative, questions: inventory[QUESTIONS].size, landmarks: inventory[LANDMARKS].size };
}

export function showTracker(rootDir, id) {
  const ctx = context(rootDir);
  const inventory = loadInventory(ctx);
  const projection = buildProjection(inventory);
  if (id === undefined) return { status: 'shown', tracker: projection };
  const found = findRecord(inventory, id);
  if (!found) refuse('unknown-identity', `No Tracker record is named ${id}.`);
  const view = found.kind === QUESTIONS
    ? projection.questions.find(card => card.id === found.record.id)
    : projection.landmarks.find(card => card.id === found.record.id);
  return { status: 'shown', id: found.record.id, kind: found.kind, record: found.record, view };
}

// ---------------------------------------------------------- human rendering

function percent(value) {
  return `${value}%`;
}

export function formatDistribution(aggregate) {
  if (aggregate.status === 'empty') return 'no items';
  const steps = STEPS.filter(step => aggregate.distribution[step] > 0).map(step => `${step} ${percent(aggregate.distribution[step])}`);
  const parts = steps.length ? steps : ['no assessed progress'];
  if (aggregate.unassessed.length) parts.push(`unassessed ${percent(aggregate.unassessedPercent)} (${aggregate.unassessed.join(', ')})`);
  return `${parts.join(', ')} over ${aggregate.items} item${aggregate.items === 1 ? '' : 's'} [${aggregate.status}]`;
}

function formatCard(card) {
  const lines = [`${card.id}  ${card.title}  (revision ${card.revision})`];
  lines.push(`  landmark: ${card.landmarkDisplay}`);
  lines.push(`  origin: "${card.origin.title}" from ${card.origin.sources.map(source => source.revision ? `${source.id}@${source.revision}` : source.id).join(', ') || 'no recorded source'}`);
  lines.push(`  answer: ${card.answered ? card.answer : 'unanswered'}`);
  if (card.expectedResult) lines.push(`  expected result: ${card.expectedResult.change}${card.expectedResult.home ? ` -> ${card.expectedResult.home}` : ''}`);
  lines.push(`  assessment: ${card.assessment.state === 'assessed' ? `${Object.entries(card.assessment.contributions).map(([step, fraction]) => `${step} ${fraction}`).join(', ')} (basis: ${card.assessment.basis})` : 'unassessed'}`);
  for (const entry of card.history) lines.push(`  r${entry.revision} ${entry.changes.map(change => change.field).join(', ')}: ${entry.reason}`);
  return lines.join('\n');
}

export function formatTracker(projection) {
  const lines = [`Workbench: ${formatDistribution(projection.workbench)}`];
  for (const landmark of projection.landmarks) lines.push(`${landmark.id}  ${landmark.title}: ${formatDistribution(landmark.aggregate)}; questions ${landmark.questions.join(', ') || 'none'}`);
  lines.push(`${projection.noLandmark.display}: ${projection.noLandmark.questions.join(', ') || 'none'}`);
  for (const card of projection.questions) lines.push(formatCard(card));
  return lines.join('\n');
}

function formatResult(command, result) {
  if (command === 'show') {
    if (result.tracker) return formatTracker(result.tracker);
    return result.kind === QUESTIONS ? formatCard(result.view) : `${result.view.id}  ${result.view.title}: ${formatDistribution(result.view.aggregate)}`;
  }
  if (command === 'rebuild') return `${result.status} ${result.projection}`;
  return `${result.status} ${result.id} (revision ${result.revision}) in ${result.record}`;
}

// --------------------------------------------------------------------- CLI

const MULTI = new Set(['source', 'uncertainty', 'resolve-uncertainty', 'correction', 'evidence']);
const COMMON = ['path'];
const OPTIONS = Object.freeze({
  capture: { positional: false, flags: ['id', 'title', 'question', 'answer', 'source', 'uncertainty', 'reason'] },
  'add-landmark': { positional: false, flags: ['id', 'title', 'summary', 'importance', 'reason'] },
  revise: { positional: true, flags: ['expect-revision', 'reason', ...new Set([...QUESTION_REVISIONS, ...LANDMARK_REVISIONS])], required: ['expect-revision'] },
  link: { positional: true, flags: ['landmark', 'expect-revision', 'reason'], required: ['landmark', 'expect-revision'] },
  rebuild: { positional: false, flags: [], booleans: ['check'] },
  show: { positional: 'optional', flags: [] }
});

export const USAGE = 'Usage: landmark-tracker.mjs capture|add-landmark|revise ID|link ID|rebuild|show [ID] [options] [--json] [--path DIR] (see workbench/landmark-tracker/README.md)';

export function parseArgs(argv) {
  const [command, ...rest] = argv;
  const spec = OPTIONS[command];
  if (!spec) throw new TrackerRefusal('invalid-invocation', USAGE);
  const accepted = [...spec.flags, ...COMMON];
  const booleans = new Set(['json', ...(spec.booleans ?? [])]);
  const options = {};
  let id;
  for (let index = 0; index < rest.length; index += 1) {
    const arg = rest[index];
    if (!arg.startsWith('--')) {
      if (!spec.positional || id !== undefined) throw new TrackerRefusal('invalid-invocation', `Unexpected argument ${arg}. ${USAGE}`);
      id = arg;
      continue;
    }
    const key = arg.slice(2);
    if (booleans.has(key)) { options[key] = true; continue; }
    if (!accepted.includes(key)) throw new TrackerRefusal('invalid-invocation', `${command} does not accept --${key}; it accepts ${[...accepted, ...booleans].map(name => `--${name}`).join(', ')}`);
    const value = rest[++index];
    if (value === undefined) throw new TrackerRefusal('invalid-invocation', `--${key} needs a value`);
    if (MULTI.has(key)) options[key] = [...(options[key] ?? []), value];
    else if (Object.hasOwn(options, key)) throw new TrackerRefusal('invalid-invocation', `--${key} was given twice`);
    else options[key] = value;
  }
  if (spec.positional === true && id === undefined) throw new TrackerRefusal('invalid-invocation', `${command} needs a record identity. ${USAGE}`);
  for (const key of spec.required ?? []) if (options[key] === undefined) throw new TrackerRefusal('invalid-invocation', `${command} requires --${key}`);
  if (options['expect-revision'] !== undefined && !/^[1-9][0-9]*$/.test(options['expect-revision'])) throw new TrackerRefusal('invalid-invocation', '--expect-revision must be a positive integer (the revision you read)');
  return { command, id, options };
}

export function runCommand(rootDir, command, id, options) {
  if (command === 'capture') return captureQuestion(rootDir, options);
  if (command === 'add-landmark') return addLandmark(rootDir, options);
  if (command === 'revise') return reviseRecord(rootDir, id, options);
  if (command === 'link') return linkLandmark(rootDir, id, options);
  if (command === 'rebuild') return rebuildTracker(rootDir, options);
  if (command === 'show') return showTracker(rootDir, id);
  throw new TrackerRefusal('invalid-invocation', USAGE);
}

if (isMainModule(import.meta.url)) {
  const argv = process.argv.slice(2);
  const json = argv.includes('--json');
  let command;
  try {
    const parsed = parseArgs(argv);
    command = parsed.command;
    const root = findRoot(parsed.options.path ?? process.cwd());
    const { path: _path, json: _json, ...options } = parsed.options;
    const result = runCommand(root, command, parsed.id, options);
    process.stdout.write(json ? `${JSON.stringify(result)}\n` : `${formatResult(command, result)}\n`);
  } catch (error) {
    const known = error instanceof TrackerRefusal;
    const failure = { status: 'blocked', error: { code: known ? error.code : 'tracker-failure', message: error.message, ...(known ? error.details : {}) } };
    if (json) process.stdout.write(`${JSON.stringify(failure)}\n`);
    else process.stderr.write(`blocked (${failure.error.code}): ${failure.error.message}\n`);
    process.exitCode = 1;
  }
}
